CREATE TABLE [dbo].[Departments]
(
	[Id] INT IDENTITY(1, 1) NOT NULL,
	[Name] NVARCHAR(MAX) COLLATE Cyrillic_General_CI_AS NOT NULL DEFAULT '',
    CONSTRAINT[PK_dbo.Departments] PRIMARY KEY CLUSTERED([Id] ASC)
)
