CREATE TABLE [dbo].[Employees]
(
	[Id] INT IDENTITY(1, 1) NOT NULL,
	[Code] INT NOT NULL DEFAULT 0,
	[Name] NVARCHAR(MAX) COLLATE Cyrillic_General_CI_AS NOT NULL DEFAULT '',
    [Age] INT NOT NULL DEFAULT 0,
	[Salary] DECIMAL NOT NULL DEFAULT 0,
	[Department] INT NOT NULL FOREIGN KEY REFERENCES Departments(Id),
    CONSTRAINT[PK_dbo.Employeees] PRIMARY KEY CLUSTERED([Id] ASC)
)

